services:
  - type: web
    name: whatsapp-auto-reply
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: WHATSAPP_API_TOKEN
        sync: false
    plan: free
